name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch (or the branch you use)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can specify the Node.js version you are using (e.g., '16')

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # This should build your project and generate the `dist` folder

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Target branch for deployment
        folder: dist      # Folder to deploy (ensure this matches the build output folder)
